#!/usr/bin/env python3
"""
Copies the shared content packages into the web app.

The chart package and the library content are authored once and consumed by
both clients: the Android app reads them straight out of its APK assets, the
web app fetches them over HTTP. Rather than duplicating the source of truth,
this script mirrors the Android asset tree into web/assets/ and writes a
listing the service worker uses to decide what to precache for offline use.
"""
import hashlib
import json
import os
import shutil
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, "android", "app", "src", "main", "assets")
DST = os.path.join(ROOT, "web", "assets")

# Glyphs are duplicated in the Android tree under percent-encoded names because
# MapLibre Native asks for them that way; the browser build only needs one form.
TREES = ["maps", "library", "glyphs"]
SKIP = {"Open%20Sans%20Bold", "Open%20Sans%20Regular", ".DS_Store"}


def copy_tree(name):
    src = os.path.join(SRC, name)
    dst = os.path.join(DST, name)
    if not os.path.isdir(src):
        sys.exit(f"kaynak yok: {src}")
    if os.path.isdir(dst):
        shutil.rmtree(dst)
    shutil.copytree(src, dst, ignore=lambda d, names: [n for n in names if n in SKIP])


def listing():
    """Relative URLs plus a content hash, so the service worker can version itself."""
    files, digest = [], hashlib.sha256()
    for base, _, names in os.walk(DST):
        for n in sorted(names):
            path = os.path.join(base, n)
            rel = os.path.relpath(path, os.path.join(ROOT, "web")).replace(os.sep, "/")
            if rel.endswith("assets/index.json"):
                continue
            files.append(rel)
            digest.update(rel.encode())
            digest.update(str(os.path.getsize(path)).encode())
    return sorted(files), digest.hexdigest()[:12]


def main():
    for tree in TREES:
        copy_tree(tree)
    files, version = listing()
    with open(os.path.join(DST, "index.json"), "w", encoding="utf-8") as fh:
        json.dump({"version": version, "files": files}, fh, ensure_ascii=False, indent=1)

    # A service worker is stopped and restarted freely, losing any state it kept
    # in module scope. Baking the cache name into a script it can importScripts()
    # keeps a restarted worker pointed at the cache it filled.
    with open(os.path.join(ROOT, "web", "sw-version.js"), "w", encoding="utf-8") as fh:
        fh.write("// Generated by tools/web/sync_assets.py — do not edit.\n")
        fh.write(f'self.CACHE_VERSION = "{version}";\n')

    total = sum(os.path.getsize(os.path.join(ROOT, "web", f)) for f in files)
    print(f"{len(files)} dosya, {total / 1_048_576:.1f} MB  (surum {version})")
    for tree in TREES:
        n = sum(1 for f in files if f.startswith(f"assets/{tree}/"))
        print(f"  assets/{tree}: {n}")


if __name__ == "__main__":
    main()
